FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=development

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer toutes les dépendances
RUN npm ci && chown -R node:node /app

# Copier le reste du code avec les bons droits
COPY --chown=node:node . .

# Utiliser l'utilisateur non-root
USER node

# Exposer le port
EXPOSE 3000

# Lancer Next.js en mode dev (hot reload)
CMD ["npm", "run", "dev"]