module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts', 'tsx'],
  rootDir: '.',
  testMatch: ['<rootDir>/tests/**/*.spec.ts'],
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
    '^.+\\.(tsx|jsx)$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.(t|j)s',
    '!src/**/*.d.ts',
    '!src/**/*.test.{ts,tsx}',
    '!src/**/*.spec.{ts,tsx}',
    '!src/main.ts',
    '!src/app.module.ts',
    '!src/app.controller.ts',
    '!src/app.service.ts',
    '!src/config/**',
    '!src/test/**',
    '!src/email-templates/**',
    '!src/**/index.ts',
    '!src/queue/queue.module.ts',
    '!src/**/*.module.ts',
    '!src/auth/auth.module.ts',
    '!src/quotes/quotes.module.ts',
    '!src/appointments/appointments.module.ts',
    '!src/backoffice/backoffice.module.ts',
    '!src/email/email.module.ts',
    '!src/email/email-actions.module.ts',
    '!src/mail/mail.module.ts',
    '!src/prisma/prisma.module.ts',
    '!src/prisma/prisma.service.ts',
    '!src/contacts/contacts.service.ts',
    '!src/auth/strategies/jwt.strategy.ts',
    '!src/appointments/dto/admin-reschedule.dto.ts',
    '!src/appointments/dto/admin-update-status.dto.ts',
    '!src/appointments/dto/create-appointment.dto.ts',
    '!src/appointments/dto/confirm-appointment.dto.ts',
    '!src/monitoring/http-metrics.interceptor.ts',
  ],
  coverageDirectory: '<rootDir>/coverage',
  testEnvironment: 'node',
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/src/test/setup.ts'],
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '^@/(.*)$': '<rootDir>/$1',
  },
};
